// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "ui.h"

Fl_Double_Window* UserInterface::make_window() {
  { window = new Fl_Double_Window(550, 400, "\350\265\204\346\272\220\345\214\205\345\210\266\344\275\234\345\231\250");
    window->user_data((void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 550, 400);
      { Fl_Group* o = new Fl_Group(45, 35, 480, 355, "\350\265\204\346\272\220\345\214\205\351\200\211\351\241\271");
        o->hide();
        { pack_name = new Fl_Input(165, 65, 300, 25, "\350\265\204\346\272\220\345\214\205\345\220\215");
        } // Fl_Input* pack_name
        { des_input = new Fl_Input(165, 120, 300, 25, "\346\217\217\350\277\260");
        } // Fl_Input* des_input
        { icon_choose = new Fl_Output(165, 175, 220, 25, "\345\233\276\346\240\207");
        } // Fl_Output* icon_choose
        { icon_browse = new Fl_Button(385, 175, 80, 25, "\346\265\217\350\247\210");
        } // Fl_Button* icon_browse
        { icon_box = new Fl_Box(165, 230, 128, 128);
        } // Fl_Box* icon_box
        o->end();
      } // Fl_Group* o
      { choose_ttf_mode = new Fl_Group(45, 35, 480, 355, "\345\255\227\344\275\223");
        { Fl_Round_Button* o = new Fl_Round_Button(165, 65, 25, 25, "\351\200\211\346\213\251Ttf\346\226\207\344\273\266");
          o->down_box(FL_ROUND_DOWN_BOX);
        } // Fl_Round_Button* o
        { choose_system_font_mode = new Fl_Round_Button(165, 175, 25, 25, "\351\200\211\346\213\251\347\263\273\347\273\237\345\255\227\344\275\223");
          choose_system_font_mode->down_box(FL_ROUND_DOWN_BOX);
        } // Fl_Round_Button* choose_system_font_mode
        { ttf_output = new Fl_Output(165, 120, 220, 25, "Ttf\346\226\207\344\273\266");
        } // Fl_Output* ttf_output
        { ttf_browse = new Fl_Button(385, 120, 80, 25, "\346\265\217\350\247\210");
        } // Fl_Button* ttf_browse
        { system_fonts_choise = new Fl_Choice(215, 230, 25, 25, "choice:");
          system_fonts_choise->down_box(FL_BORDER_BOX);
        } // Fl_Choice* system_fonts_choise
        choose_ttf_mode->end();
      } // Fl_Group* choose_ttf_mode
      o->end();
    } // Fl_Tabs* o
    window->end();
  } // Fl_Double_Window* window
  return window;
}
