// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Choice.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *window;
  Fl_Input *pack_name;
  Fl_Input *des_input;
  Fl_Output *icon_choose;
  Fl_Button *icon_browse;
  Fl_Box *icon_box;
  Fl_Group *choose_ttf_mode;
  Fl_Round_Button *choose_system_font_mode;
  Fl_Output *ttf_output;
  Fl_Button *ttf_browse;
  Fl_Choice *system_fonts_choise;
};
#endif
